import Head from "next/head";


export default function Home() {
  return (
    <>
    <Head>
      <title>Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width-device-width, initial-scale-1" />
      <link rel="stylesheet" href="/favicon.ico" />
    </Head>

    <main >
      <div className="font-bodyFont">New Portfolio Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit perferendis laborum deserunt nisi quod natus dolor! Iste maiores est modi recusandae provident. Nobis dolorum at totam aliquam molestias consectetur odit.
      </div>
    </main>
    </>
  )
}
